praktikum/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story4/', include(('story_4.urls', 'story4'), namespace="story_4")),
    path('story6/', include(('story_6.urls', 'story6'), namespace="story_6")),
    path('story7/', include(('story_7.urls', 'story7'), namespace="story_7")),
    path('story8/', include(('story_8.urls', 'story8'), namespace="story_8")),
    path('story9/', include(('story_9.urls', 'story9'), namespace="story_9"))
]

story_4/urls.py
from django.conf.urls import re_path
from .views import index, activities, add_message, delete_todo

#url for app
urlpatterns = [
	re_path(r'^$', index, name='index'),
	re_path(r'^activities/$',  activities, name='activities'),
	re_path(r'^add_message/$', add_message, name='add_message'),
	re_path(r'^(?P<id>[0-9]+)/delete/$', delete_todo, name='delete_todo')
]

story_9/urls.py
from django.contrib import admin
from django.urls import re_path
from .views import index, log_in, log_out

#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
	re_path(r'^log_in/$', log_in, name='log_in'),
    re_path(r'^log_out/$', log_out, name='log_out')
]

story_9/models.py
from django.db import models

# Create your models here.
class data_login(models.Model):
    username = models.CharField(max_length=20, null=True)
    email = models.EmailField(max_length=50, primary_key=True, unique=True)
    password = models.CharField(max_length=12)

story_9/forms.py
from django import forms

class form_login(forms.Form):
    username = forms.CharField(required=True, max_length=20, widget=forms.TextInput(attrs={'type' : 'username', 'placeholder' : 'your_name', 'label' : 'username',  'id' : 'username'}))
    email = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={'type' : 'email', 'placeholder' : 'example@email.com', 'label' : 'email', 'id' : 'email'}))
    password = forms.CharField(required=True, min_length=8, max_length=12, widget=forms.TextInput(attrs={'type' : 'password', 'placeholder' : 'Password', 'label' : 'Password', 'id' : 'password'}))

story_9/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import data_login
from .forms import form_login
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

# Create your views here.
response = {}
def index(request):
    status_login = 'username' in request.session
    Form = form_login()
    if status_login:
        response['message_success'] = 'Selamat datang, ' +  request.session['username']
    response['status_login'] = status_login
    response['form'] = Form
    return render(request, 'login.html', response)

def log_in(request):
    print("login")
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        validasi = data_login.objects.filter(pk=email)
        if len(validasi) != 0:
            request.session['username'] = username
            request.session['user_email'] = email
            request.session['user_password'] = password
            return redirect('/story9/')
        else :
            messages.error(request, 'Username/email/password salah')
            return redirect('/story9/')

def log_out(request):
    request.session.flush()
    return redirect('/story9/')

story_9/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Log in Page</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

    </head>
    <body id='body'>
        
        <div class="container">
            <div class="content">
                {% if status_login %}
                    <div><h3 style="color: white">{{ message_success }}</h3>
                    <a href="{% url 'story_9:log_out' %}" id="logout" class="btn btn-primary"> <i aria-hidden="true"></i>Log out</a></div>
                {% else %}
                        <div><h2 class="judul">Log In</h2></div>
                        <div class="content-form"><form class="form_input" method="POST" class="isi" action="{% url 'story_9:log_in' %}">
                            {% csrf_token %}
                            <div style="color: #161670" class="validate-input" data-validate="Username is required">
                                {{ form.username.label_tag }}
                                {{ form.username }}
                            </div>
                            <div style="color: #161670" class="validate-input" data-validate="Valid email is required" data-validate2="Email already registered">
                                {{ form.email.label_tag }}
                                {{ form.email }}
                            </div>
                            <div style="color: #161670" class="validate-input" data-validate="Password is required">
                                {{ form.password.label_tag }}
                                {{ form.password }}
                            </div>
                            <button class="submit" id="login" type="submit">Log in</button>
                            <br><br>
                        </form></div>
                        {% if messages %}
                            <div class="notifications">
                                {% for message in messages %}
                                <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                {% endif %}
            </div>
        </div>

    </body>
</html>